-- A random public address for BookingIntent, replacing the cuid primary key in the flow URL.
--
-- `/practitioners/[slug]/book/[token]` is public and unauthenticated, so whatever sits in that URL
-- IS the credential. Using `id` meant that credential was a cuid: `c` + a base36 millisecond
-- timestamp + a monotonic counter + a per-process host fingerprint + a small random block. Ids
-- minted in a known window are therefore enumerable at far better than random odds, and a hit
-- renders the buyer's first name, the offering they chose, and the practitioner's scheduler URL.
--
-- §10's resume email is what makes this urgent rather than theoretical: it puts these URLs into
-- inboxes, where they are forwarded, archived and machine-scanned. Enumeration is also unthrottled
-- in practice, because rateLimit() no-ops whenever KV is unprovisioned — which it is on production.
--
-- Written in four steps rather than one so it is safe under expand/contract. Migrations apply
-- during the build while the PREVIOUS deployment is still serving traffic and still inserting
-- BookingIntent rows that know nothing about this column: adding it NOT NULL in one shot would
-- fail every capture for the length of the build, on a live revenue path. So the column arrives
-- nullable, existing rows are filled, a DB-level DEFAULT covers the old code's inserts, and only
-- then does NOT NULL apply.
--
-- Two concatenated v4 uuids, hyphens stripped: 64 hex chars, ~244 bits of randomness, generated by
-- Postgres so the application can never forget to supply one. gen_random_uuid() is built in from
-- PG13 (Neon is well past that) — no pgcrypto extension required.
ALTER TABLE "BookingIntent" ADD COLUMN "publicToken" TEXT;

UPDATE "BookingIntent"
   SET "publicToken" = replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '')
 WHERE "publicToken" IS NULL;

ALTER TABLE "BookingIntent"
  ALTER COLUMN "publicToken"
  SET DEFAULT (replace((gen_random_uuid())::text, '-'::text, ''::text) || replace((gen_random_uuid())::text, '-'::text, ''::text));

ALTER TABLE "BookingIntent" ALTER COLUMN "publicToken" SET NOT NULL;

CREATE UNIQUE INDEX "BookingIntent_publicToken_key" ON "BookingIntent"("publicToken");
